# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Taps for Veteran Funerals"
title_end: " | TAPPS Nevada"
email: tappsnevadacalendar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We perform "Taps" at military funerals and other patriotic events throughout the Las Vegas valley. Our organization gives back one last time to those who chose to serve our nation in the United States military.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.tappsnevada.org" # the base hostname & protocol for your site, e.g. http://example.com
imgurl: "/assets/images/" # the subpath for the image directory
twitter_username: "tappsnevada"
fb_username: "TAPPSNevada"
google_analytics: "UA-109686984-1"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .git/
  - README.md
  - .DS_Store